// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirm": {
            "post": {
                "description": "Verifies the 6-digit OTP code against the active Redis session. If valid, completes the requested action (creates user, updates password, or activates profile) and issues session tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm OTP code for registration, login or recovery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003csession_token\u003e (Validated via Session Middleware)",
                        "name": "X-Session-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workflow action: register, login, recovery_user, or recovery_password",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Confirmation payload (NewPassword is required only for recovery_password)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestConfirm"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created (for action=register) or successfully processed (200 OK for other actions)",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_auth.ResponseConfirm"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Client validation errors. Format: { \\\"errors\\\": { \\\"code\\\": \\\"the code must be 6 characters\\\" } } or { \\\"errors\\\": { \\\"action\\\": \\\"the action must be register, login or recovery\\\" } } or { \\\"errors\\\": { \\\"session\\\": \\\"incorrect session id\\\" } } or { \\\"errors\\\": { \\\"user\\\": \\\"user already exist\\\" } } or { \\\"errors\\\": { \\\"new_password\\\": \\\"new password not specified\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication or session errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid session token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"authorization session has expired or does not exist\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect code\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"user\\\": \\\"not found user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to ensure security\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Verifies credentials using bcrypt against PostgreSQL and issues a secure session token pair via internal workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestLogin"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Authentication accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_auth-service_internal_common.ResponseAuth"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation errors. Format: { \\\"errors\\\": { \\\"email\\\": \\\"incorrect email\\\" } } or { \\\"errors\\\": { \\\"password\\\": \\\"password must be between 8 and 24 characters\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Incorrect credentials. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect password or email\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to ensure security\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Parses the refresh token from request body, extracts session UUID, and safely deletes the active session from Redis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout user and invalidate session",
                "parameters": [
                    {
                        "description": "Logout payload containing refresh token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestRefreshLogout"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Session successfully invalidated, no content returned"
                    },
                    "400": {
                        "description": "Client validation errors. Format: { \\\"errors\\\": { \\\"refresh_token\\\": \\\"refresh token not sent\\\" } } or { \\\"errors\\\": { \\\"body\\\": \\\"invalid json format\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/recovery": {
            "post": {
                "description": "Initiates recovery process (recovery_password or recovery_user) via email verification. For account recovery, requires active password validation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Recover user account or password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of recovery: recovery_password or recovery_user",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Recovery payload (Password is required only for recovery_user)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestRecovery"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Recovery process accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_auth-service_internal_common.ResponseAuth"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Client validation errors. Format: { \\\"errors\\\": { \\\"email\\\": \\\"incorrect email\\\" } } or { \\\"errors\\\": { \\\"action\\\": \\\"action must be recovery_password or recovery_user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"password is empty\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect password or email\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"email\\\": \\\"not found user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to ensure security\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Parses old appjwt refresh token from body, validates session UUID and User-Agent in Redis, and performs safe Token Rotation using WATCH locking.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rotate refresh token",
                "parameters": [
                    {
                        "description": "Refresh token payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestRefreshLogout"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tokens successfully rotated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_auth.ResponseConfirm"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Client validation errors. Format: { \\\"errors\\\": { \\\"refresh_jwt\\\": \\\"refresh token not sent\\\" } } or { \\\"errors\\\": { \\\"body\\\": \\\"invalid json format\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Token or session expired errors. Format: { \\\"errors\\\": { \\\"refresh_token\\\": \\\"refresh token renewal error\\\" } } or { \\\"errors\\\": { \\\"refresh_token\\\": \\\"session has expired try again later\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Validates name length, strong password policy, and email uniqueness before triggering internal registration workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RequestRegister"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "User registration process accepted",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_auth-service_internal_common.ResponseAuth"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Client validation errors. Format: { \\\"errors\\\": { \\\"name\\\": \\\"name must be between 2 and 64 characters\\\" } } or { \\\"errors\\\": { \\\"email\\\": \\\"incorrect email\\\" } } or { \\\"errors\\\": { \\\"password\\\": \\\"password must be between 8 and 24 characters\\\" } } or { \\\"errors\\\": { \\\"user\\\": \\\"user already exist\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to ensure security\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "Retrieves current authenticated user's profile details from MySQL by UUID stored in appjwt access token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User profile details successfully retrieved",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.ResponseUser"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Token errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"access token has expired\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"user\\\": \\\"not found user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to get user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Validates user credentials and the deletion type. If criteria are met, generates a confirmation session in Redis and triggers 2FA workflow (returns 202 Accepted).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Initiate account deletion workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type of deletion: soft-delete or hard-delete",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Account credentials payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.RequestRemoveUser"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Deletion request accepted, 2FA confirmation workflow initiated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_auth-service_internal_common.ResponseAuth"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Client validation errors. Format: { \\\"errors\\\": { \\\"email\\\": \\\"incorrect email\\\" } } or { \\\"errors\\\": { \\\"action\\\": \\\"the type  must be a soft-delete or hard-delete\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect password or email\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to remove user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates public info directly (returns 200 OK). If updating sensitive info (email/password), requires current password and triggers 2FA workflow (returns 202 Accepted).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update user profile data or trigger sensitive update workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Profile update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.RequestUpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Public profile details successfully updated instantly",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_auth-service_internal_model.Users"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "202": {
                        "description": "Sensitive update accepted, 2FA confirmation workflow initiated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/app_auth-service_internal_common.ResponseAuth"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Validation or business logic errors. Format: { \\\"errors\\\": { \\\"new_name\\\": \\\"new name must be between 2 and 64 characters\\\" } } or { \\\"errors\\\": { \\\"new_password\\\": \\\"the new_password cannot  contain email\\\" } } or { \\\"errors\\\": { \\\"email\\\": \\\"either a new email or an old one must be present\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect password or email\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"user\\\": \\\"not found user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to update user\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to ensure security\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        },
        "/user/confirm": {
            "post": {
                "description": "Validates the 6-digit OTP code from Redis session. For updates, applies changes to MySQL and returns user data (200 OK). For hard/soft deletion, purges sessions, publishes to Kafka, and returns no content (204 No Content).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Confirm 2FA code for profile updates or account deletion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workflow action: update, soft-delete, or hard-delete",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Confirmation payload storing 6-digit code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_user.RequestConfirm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sensitive profile details successfully updated",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_user.ResponseUser"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "204": {
                        "description": "Account successfully deleted (soft or hard), no content returned"
                    },
                    "400": {
                        "description": "Client validation or workflow errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"the code must be 6 characters\\\" } } or { \\\"errors\\\": { \\\"action\\\": \\\"the action must be update, soft-delete or hard-delete\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication or session errors. Format: { \\\"errors\\\": { \\\"auth\\\": \\\"invalid access token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"refresh token has expired\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect refresh token\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"refresh token renewal error\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect session id\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"authorization session has expired or does not exist\\\" } } or { \\\"errors\\\": { \\\"auth\\\": \\\"incorrect code\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "404": {
                        "description": "Data errors. Format: { \\\"errors\\\": { \\\"user\\\": \\\"not found user\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "429": {
                        "description": "Too many requests. Format: { \\\"errors\\\": { \\\"global\\\": \\\"the limit for sending requests per minute has been exceeded\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    },
                    "500": {
                        "description": "Server errors. Format: { \\\"errors\\\": { \\\"global\\\": \\\"failed to update user\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to delete user\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"failed to remove user\\\" } } or { \\\"errors\\\": { \\\"global\\\": \\\"critical error on the server side\\\" } }",
                        "schema": {
                            "$ref": "#/definitions/response.NegativeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_auth-service_internal_common.ResponseAuth": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "session_jwt": {
                    "type": "string"
                }
            }
        },
        "app_auth-service_internal_model.Users": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userUUID": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_auth.RequestConfirm": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "integer",
                    "maximum": 999999,
                    "minimum": 100000
                },
                "new_password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                }
            }
        },
        "internal_auth.RequestLogin": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                }
            }
        },
        "internal_auth.RequestRecovery": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                }
            }
        },
        "internal_auth.RequestRefreshLogout": {
            "type": "object",
            "required": [
                "refresh_jwt"
            ],
            "properties": {
                "refresh_jwt": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RequestRegister": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                }
            }
        },
        "internal_auth.ResponseConfirm": {
            "type": "object",
            "properties": {
                "access_jwt": {
                    "type": "string"
                },
                "refresh_jwt": {
                    "type": "string"
                }
            }
        },
        "internal_user.RequestConfirm": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "integer",
                    "maximum": 999999,
                    "minimum": 100000
                },
                "refresh_jwt": {
                    "type": "string"
                }
            }
        },
        "internal_user.RequestRemoveUser": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                }
            }
        },
        "internal_user.RequestUpdateUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "new_email": {
                    "type": "string"
                },
                "new_name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 2
                },
                "new_password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                },
                "password": {
                    "type": "string",
                    "maxLength": 24,
                    "minLength": 8
                }
            }
        },
        "internal_user.ResponseUser": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userUUID": {
                    "type": "string"
                }
            }
        },
        "response.NegativeResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "tags": [
        {
            "description": "User registration, authentication, and session management",
            "name": "auth"
        },
        {
            "description": "Profile management, account data retrieval, and user deletion logs",
            "name": "user"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Auth & User Microservice API",
	Description:      "Core authentication and identity service with token rotation, profile management, and sliding window rate limiting.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
