// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shared/shprotos/event/letter.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*NotificationEvent_AuthCode
	//	*NotificationEvent_NewDevice
	//	*NotificationEvent_SecurityAlert
	Event         isNotificationEvent_Event `protobuf_oneof:"event"`
	EmailTo       string                    `protobuf:"bytes,5,opt,name=EmailTo,proto3" json:"EmailTo,omitempty"`
	EventUUID     string                    `protobuf:"bytes,6,opt,name=EventUUID,proto3" json:"EventUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_shared_shprotos_event_letter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_shprotos_event_letter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_shared_shprotos_event_letter_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationEvent) GetEvent() isNotificationEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NotificationEvent) GetAuthCode() *AuthLetterPayload {
	if x != nil {
		if x, ok := x.Event.(*NotificationEvent_AuthCode); ok {
			return x.AuthCode
		}
	}
	return nil
}

func (x *NotificationEvent) GetNewDevice() *SecurityLetterPayload {
	if x != nil {
		if x, ok := x.Event.(*NotificationEvent_NewDevice); ok {
			return x.NewDevice
		}
	}
	return nil
}

func (x *NotificationEvent) GetSecurityAlert() *SecurityLetterPayload {
	if x != nil {
		if x, ok := x.Event.(*NotificationEvent_SecurityAlert); ok {
			return x.SecurityAlert
		}
	}
	return nil
}

func (x *NotificationEvent) GetEmailTo() string {
	if x != nil {
		return x.EmailTo
	}
	return ""
}

func (x *NotificationEvent) GetEventUUID() string {
	if x != nil {
		return x.EventUUID
	}
	return ""
}

type isNotificationEvent_Event interface {
	isNotificationEvent_Event()
}

type NotificationEvent_AuthCode struct {
	AuthCode *AuthLetterPayload `protobuf:"bytes,1,opt,name=auth_code,json=authCode,proto3,oneof"`
}

type NotificationEvent_NewDevice struct {
	NewDevice *SecurityLetterPayload `protobuf:"bytes,2,opt,name=new_device,json=newDevice,proto3,oneof"`
}

type NotificationEvent_SecurityAlert struct {
	SecurityAlert *SecurityLetterPayload `protobuf:"bytes,3,opt,name=security_alert,json=securityAlert,proto3,oneof"`
}

func (*NotificationEvent_AuthCode) isNotificationEvent_Event() {}

func (*NotificationEvent_NewDevice) isNotificationEvent_Event() {}

func (*NotificationEvent_SecurityAlert) isNotificationEvent_Event() {}

type AuthLetterPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidTime     int64                  `protobuf:"varint,1,opt,name=ValidTime,proto3" json:"ValidTime,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLetterPayload) Reset() {
	*x = AuthLetterPayload{}
	mi := &file_shared_shprotos_event_letter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLetterPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLetterPayload) ProtoMessage() {}

func (x *AuthLetterPayload) ProtoReflect() protoreflect.Message {
	mi := &file_shared_shprotos_event_letter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLetterPayload.ProtoReflect.Descriptor instead.
func (*AuthLetterPayload) Descriptor() ([]byte, []int) {
	return file_shared_shprotos_event_letter_proto_rawDescGZIP(), []int{1}
}

func (x *AuthLetterPayload) GetValidTime() int64 {
	if x != nil {
		return x.ValidTime
	}
	return 0
}

func (x *AuthLetterPayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SecurityLetterPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	CurrentTime   string                 `protobuf:"bytes,3,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityLetterPayload) Reset() {
	*x = SecurityLetterPayload{}
	mi := &file_shared_shprotos_event_letter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityLetterPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityLetterPayload) ProtoMessage() {}

func (x *SecurityLetterPayload) ProtoReflect() protoreflect.Message {
	mi := &file_shared_shprotos_event_letter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityLetterPayload.ProtoReflect.Descriptor instead.
func (*SecurityLetterPayload) Descriptor() ([]byte, []int) {
	return file_shared_shprotos_event_letter_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityLetterPayload) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SecurityLetterPayload) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SecurityLetterPayload) GetCurrentTime() string {
	if x != nil {
		return x.CurrentTime
	}
	return ""
}

var File_shared_shprotos_event_letter_proto protoreflect.FileDescriptor

const file_shared_shprotos_event_letter_proto_rawDesc = "" +
	"\n" +
	"\"shared/shprotos/event/letter.proto\x12\x05event\"\x93\x02\n" +
	"\x11NotificationEvent\x127\n" +
	"\tauth_code\x18\x01 \x01(\v2\x18.event.AuthLetterPayloadH\x00R\bauthCode\x12=\n" +
	"\n" +
	"new_device\x18\x02 \x01(\v2\x1c.event.SecurityLetterPayloadH\x00R\tnewDevice\x12E\n" +
	"\x0esecurity_alert\x18\x03 \x01(\v2\x1c.event.SecurityLetterPayloadH\x00R\rsecurityAlert\x12\x18\n" +
	"\aEmailTo\x18\x05 \x01(\tR\aEmailTo\x12\x1c\n" +
	"\tEventUUID\x18\x06 \x01(\tR\tEventUUIDB\a\n" +
	"\x05event\"E\n" +
	"\x11AuthLetterPayload\x12\x1c\n" +
	"\tValidTime\x18\x01 \x01(\x03R\tValidTime\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\"o\n" +
	"\x15SecurityLetterPayload\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12!\n" +
	"\fcurrent_time\x18\x03 \x01(\tR\vcurrentTimeB\x1dZ\x1bshared/shprotos/event;eventb\x06proto3"

var (
	file_shared_shprotos_event_letter_proto_rawDescOnce sync.Once
	file_shared_shprotos_event_letter_proto_rawDescData []byte
)

func file_shared_shprotos_event_letter_proto_rawDescGZIP() []byte {
	file_shared_shprotos_event_letter_proto_rawDescOnce.Do(func() {
		file_shared_shprotos_event_letter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_shprotos_event_letter_proto_rawDesc), len(file_shared_shprotos_event_letter_proto_rawDesc)))
	})
	return file_shared_shprotos_event_letter_proto_rawDescData
}

var file_shared_shprotos_event_letter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_shprotos_event_letter_proto_goTypes = []any{
	(*NotificationEvent)(nil),     // 0: event.NotificationEvent
	(*AuthLetterPayload)(nil),     // 1: event.AuthLetterPayload
	(*SecurityLetterPayload)(nil), // 2: event.SecurityLetterPayload
}
var file_shared_shprotos_event_letter_proto_depIdxs = []int32{
	1, // 0: event.NotificationEvent.auth_code:type_name -> event.AuthLetterPayload
	2, // 1: event.NotificationEvent.new_device:type_name -> event.SecurityLetterPayload
	2, // 2: event.NotificationEvent.security_alert:type_name -> event.SecurityLetterPayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shared_shprotos_event_letter_proto_init() }
func file_shared_shprotos_event_letter_proto_init() {
	if File_shared_shprotos_event_letter_proto != nil {
		return
	}
	file_shared_shprotos_event_letter_proto_msgTypes[0].OneofWrappers = []any{
		(*NotificationEvent_AuthCode)(nil),
		(*NotificationEvent_NewDevice)(nil),
		(*NotificationEvent_SecurityAlert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_shprotos_event_letter_proto_rawDesc), len(file_shared_shprotos_event_letter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_shprotos_event_letter_proto_goTypes,
		DependencyIndexes: file_shared_shprotos_event_letter_proto_depIdxs,
		MessageInfos:      file_shared_shprotos_event_letter_proto_msgTypes,
	}.Build()
	File_shared_shprotos_event_letter_proto = out.File
	file_shared_shprotos_event_letter_proto_goTypes = nil
	file_shared_shprotos_event_letter_proto_depIdxs = nil
}
