// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shared/shprotos/event/user.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserDataEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuidList  []string               `protobuf:"bytes,1,rep,name=user_uuid_list,json=userUuidList,proto3" json:"user_uuid_list,omitempty"`
	EventUuid     string                 `protobuf:"bytes,2,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserDataEvent) Reset() {
	*x = DeleteUserDataEvent{}
	mi := &file_shared_shprotos_event_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserDataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserDataEvent) ProtoMessage() {}

func (x *DeleteUserDataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_shprotos_event_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserDataEvent.ProtoReflect.Descriptor instead.
func (*DeleteUserDataEvent) Descriptor() ([]byte, []int) {
	return file_shared_shprotos_event_user_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserDataEvent) GetUserUuidList() []string {
	if x != nil {
		return x.UserUuidList
	}
	return nil
}

func (x *DeleteUserDataEvent) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

var File_shared_shprotos_event_user_proto protoreflect.FileDescriptor

const file_shared_shprotos_event_user_proto_rawDesc = "" +
	"\n" +
	" shared/shprotos/event/user.proto\x12\x05event\"Z\n" +
	"\x13DeleteUserDataEvent\x12$\n" +
	"\x0euser_uuid_list\x18\x01 \x03(\tR\fuserUuidList\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x02 \x01(\tR\teventUuidB\x1dZ\x1bshared/shprotos/event;eventb\x06proto3"

var (
	file_shared_shprotos_event_user_proto_rawDescOnce sync.Once
	file_shared_shprotos_event_user_proto_rawDescData []byte
)

func file_shared_shprotos_event_user_proto_rawDescGZIP() []byte {
	file_shared_shprotos_event_user_proto_rawDescOnce.Do(func() {
		file_shared_shprotos_event_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_shprotos_event_user_proto_rawDesc), len(file_shared_shprotos_event_user_proto_rawDesc)))
	})
	return file_shared_shprotos_event_user_proto_rawDescData
}

var file_shared_shprotos_event_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_shprotos_event_user_proto_goTypes = []any{
	(*DeleteUserDataEvent)(nil), // 0: event.DeleteUserDataEvent
}
var file_shared_shprotos_event_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_shprotos_event_user_proto_init() }
func file_shared_shprotos_event_user_proto_init() {
	if File_shared_shprotos_event_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_shprotos_event_user_proto_rawDesc), len(file_shared_shprotos_event_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_shprotos_event_user_proto_goTypes,
		DependencyIndexes: file_shared_shprotos_event_user_proto_depIdxs,
		MessageInfos:      file_shared_shprotos_event_user_proto_msgTypes,
	}.Build()
	File_shared_shprotos_event_user_proto = out.File
	file_shared_shprotos_event_user_proto_goTypes = nil
	file_shared_shprotos_event_user_proto_depIdxs = nil
}
